
export const SET_DOMAIN_SEARCH = 'SET_DOMAIN_SEARCH';
export const SAVE_DOMAIN_SEARCH = 'SAVE_DOMAIN_SEARCH';
export const CLEAR_DOMAIN_SEARCH = 'CLEAR_DOMAIN_SEARCH';
export const REMOVE_DOMAIN_SEARCH = 'REMOVE_DOMAIN_SEARCH';