
export const SET_DOMAIN_SEARCH = 'SET_DOMAIN_SEARCH';
export const SAVE_DOMAIN_SEARCH = 'SAVE_DOMAIN_SEARCH';
export const CLEAR_DOMAIN_SEARCH = 'CLEAR_DOMAIN_SEARCH';
export const REMOVE_DOMAIN_SEARCH = 'REMOVE_DOMAIN_SEARCH';

export const DEPLOY_DOMAIN_PROXY = 'DEPLOY_DOMAIN_PROXY';
export const DOMAIN_PROXY_DEPLOYED = 'DOMAIN_PROXY_DEPLOYED';
export const DOMAIN_PROXY_MINED = 'DOMAIN_PROXY_MINED';